version: 0.2
phases:
 build:
   commands:
     - echo Build started on `date`
     - echo "Amazon CodeBuild sample-project Build- ${CODEBUILD_WEBHOOK_TRIGGER}"
     - echo $BRANCH_NAME
     - echo $REPO
